[update] gibuu-builder

diff --git a/container/gibuu-builder b/container/gibuu-builder
--- a/container/gibuu-builder
+++ b/container/gibuu-builder
@@ -1,16 +1,25 @@
 #!/bin/bash
 
-ROOT_DL="https://root.cern/download/root_v6.36.02.Linux-ubuntu24.04-x86_64-gcc13.3.tar.gz"
-GIBUU_DL="https://github.com/kvtsang/GiBUU/archive/refs/heads/main.zip"
-ROOTTUPLE_DL="https://github.com/kvtsang/GiBUU-RootTuple/archive/refs/heads/main.zip"
+root_download_url="https://root.cern.ch/download/\
+root_v6.38.04.Linux-ubuntu24.04-x86_64-gcc13.3.tar.gz"
+GIBUU_DL="https://github.com/kvtsang/GiBUU.git"
+ROOTTUPLE_DL="https://github.com/kvtsang/GiBUU-RootTuple.git"
 BUUINPUT_DL="https://gibuu.hepforge.org/downloads?f=buuinput2025.tar.gz"
 
-GIBUU_DIR="GiBUU-main"
-ROOTTUPLE_DIR="GiBUU-RootTuple-main"
+GIBUU_BRANCH="hepforge"
+ROOTTUPLE_BRANCH="hepforge"
 
 die() {
   echo "$@" >&2
   exit 1
+}
+
+git_clone() {
+  local url="$1"
+  local branch="$2"
+  local dest="$3"
+  git clone --branch "$branch" --depth 1 "$url" "$dest" \
+	  || die "Fail to clone $url"
 }
 
 help() {
@@ -26,10 +35,10 @@ Usage
 =====
 $PROGRAM download
     Download following files to current directory:
-    - $ROOT_DL
-    - $GIBUU_DL
-    - $ROOTTUPLE_DL
-    - $BUUINPUT_DL
+    - $root_download_url (wget)
+    - $GIBUU_DL → release/ (git clone)
+    - $ROOTTUPLE_DL → libraries/RootTuple/ (git clone)
+    - $BUUINPUT_DL (wget)
 
 $PROGRAM checksum
     Run md5sum on the downloaded files.
@@ -43,17 +52,15 @@ $PROGRAM build
 $PROGRAM install [DEST]
     Install GiBUU.x to DEST directory.
 
-$PROGRAM clean
-    Remove downloaded files. Only keeping the GiBUU.x binary and BUUInput data.
 _EOF
 }
 
 download() {
   echo "Downloading ..."
-  wget $ROOT_DL \
-  && wget $GIBUU_DL -O gibuu.zip \
-  && wget $ROOTTUPLE_DL -O roottuple.zip \
-  && wget --content-disposition $BUUINPUT_DL -O buuinput.tar.gz
+  wget -N "$root_download_url" \
+  && git_clone "$GIBUU_DL" "$GIBUU_BRANCH" release \
+  && git_clone "$ROOTTUPLE_DL" "$ROOTTUPLE_BRANCH" libraries/RootTuple \
+  && wget -N --content-disposition "$BUUINPUT_DL"
 
   [[ $? -ne 0 ]] && die "Fail to download file(s)"
 }
@@ -61,10 +68,8 @@ download() {
 checksum() {
   MD5SUM=$(mktemp)
   cat <<-_EOF > $MD5SUM
-0a36db2dcb99975215a82dee1c338bc2  buuinput.tar.gz
-ed5dd1345c28f19d70b58c905ce15438  root_v6.36.02.Linux-ubuntu24.04-x86_64-gcc13.3.tar.gz
-0d94ad9b52905fdae32f53dfb68ec6f3  gibuu.zip
-f61b8d5d621043a35fe651ec8e217301  roottuple.zip
+6d8d5c432008831ddeea38e7b91550ee  buuinput2025.tar.gz
+af241e9b4aeb93f6fedfb5d360b31494  root_v6.38.04.Linux-ubuntu24.04-x86_64-gcc13.3.tar.gz
 _EOF
 
   md5sum -c $MD5SUM && rm -f $MD5SUM || die
@@ -72,21 +77,13 @@ _EOF
 
 unpack() {
   echo "Unpacking ROOT ..."
-  tar zxf $(basename $ROOT_DL) || die "Fail to unpack ROOT"
+  tar zxf $(basename "$root_download_url") || die "Fail to unpack ROOT"
 
-  echo "Unpacking GiBUU ..."
+  echo "Setting up GiBUU ..."
 
-  mkdir gibuu && cd gibuu \
-  && unzip -q ../gibuu.zip \
-  && unzip -q ../roottuple.zip \
-  && tar zxf ../buuinput.tar.gz
+  tar zxf buuinput2025.tar.gz
 
   [[ $? -ne 0 ]] && die "Fail to unpack GiBUU"
-
-  mkdir -p libraries \
-  && mv $ROOTTUPLE_DIR libraries/RootTuple
-
-  [[ $? -ne 0 ]] && die "Fail to create libraries/RootTuple"
 
   exit 0
 }
@@ -94,7 +91,7 @@ unpack() {
 build() {
   source root/bin/thisroot.sh
 
-  cd gibuu/${GIBUU_DIR}
+  cd release
 
   mkdir -p objects/LIB/lib \
   && make -j $(nproc) buildRootTuple \
@@ -105,24 +102,14 @@ install() {
   DEST=${1:-./}
   echo "Copying GiBUU.x to $DEST"
 
-  mkdir -p $DEST && cp gibuu/${GIBUU_DIR}/objects/GiBUU.x $DEST
+  mkdir -p $DEST && cp release/objects/GiBUU.x $DEST
   [[ $? -ne 0 ]] && die "Fail to copy GiBUU.x"
 
   exit 0
 }
 
-clean() {
-  echo "Removing downloads and source files ..."
-  rm -f $(basename $ROOT_DL)
-  rm -f gibuu.zip
-  rm -f roottuple.zip
-  rm -f buuinput.tar.gz
-  rm -rf gibuu/libraries
-  rm -rf gibuu/${GIBUU_DIR}
-}
-
 usage() {
-  echo "$PROGRAM downlaod|checksum|unpack|build|install|clean|help [DEST]"
+  echo "$PROGRAM downlaod|checksum|unpack|build|install|help [DEST]"
 }
 
 PROGRAM="${0##*/}"
@@ -133,7 +120,6 @@ case "$1" in
   unpack)   shift; unpack "$@" ;; 
   build)    shift; build "$@" ;; 
   install)  shift; install "$@" ;;
-  clean)    shift; clean "$@" ;;
   help)     shift; help ;;
   *)        usage ;;
 esac
